# Generated by Django 3.2.9 on 2023-03-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastrovagas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=200, verbose_name='Cargo')),
                ('empresa', models.CharField(max_length=200, verbose_name='Empresa')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição')),
                ('vagas', models.CharField(max_length=10, verbose_name='Quantidade de vagas')),
                ('escolaridade', models.CharField(choices=[('Ensino Fundamental Incompleto', 'Ensino Fundamental Incompleto'), ('Ensino Fundamental Completo', 'Ensino Fundamental Completo'), ('Ensino Médio Completo', 'Ensino Médio Completo'), ('Ensino Superior Incompleto', 'Ensino Superior Incompleto'), ('Ensino Superior completo', 'Ensino Superior completo')], default='Ensino Médio Completo', max_length=30, verbose_name='Escolaridade')),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Salário')),
                ('modelo', models.CharField(choices=[('Home Office', 'Home Office'), ('Hibrido', 'Híbrido'), ('Presencial', 'Presencial')], default='Presencial', max_length=11, verbose_name='Modelo de trabalho')),
                ('localizacao', models.CharField(max_length=30, verbose_name='Localização')),
                ('horassemanais', models.CharField(max_length=6, verbose_name='Horas semanais')),
            ],
        ),
    ]
