# Generated by Django 3.2.8 on 2022-05-16 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computacao2', '0003_auto_20220508_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nomeproduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameproduto', models.CharField(max_length=200, verbose_name='Produto')),
            ],
        ),
        migrations.RemoveField(
            model_name='servicos',
            name='clientname',
        ),
        migrations.AddField(
            model_name='servicos',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='computacao2.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computacao2.nomeproduto'),
        ),
    ]
