# Generated by Django 3.2.8 on 2022-05-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computacao2', '0005_rename_title_produto_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicos',
            name='estado',
            field=models.CharField(choices=[('Não realizado', 'Não realizado'), ('Concluído', 'Concluído')], default='Não realizado', max_length=15),
        ),
    ]
