# Generated by Django 3.2.8 on 2022-05-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computacao2', '0007_produto_valornota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicos',
            name='servico',
            field=models.TextField(max_length=300, verbose_name='Serviço a ser executado'),
        ),
    ]
