# Generated by Django 3.2.8 on 2022-05-31 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computacao2', '0008_alter_servicos_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Titulo')),
                ('politicas', models.TextField(max_length=300, verbose_name='Serviço a ser executado')),
            ],
        ),
    ]
