# Generated by Django 3.2.8 on 2022-06-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computacao2', '0009_gestao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='garantia',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='item',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='nomeproduto',
            name='garantia',
            field=models.CharField(default='', max_length=10, verbose_name='Garantia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nomeproduto',
            name='marca',
            field=models.CharField(default='', max_length=10, verbose_name='Marca do produto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nomeproduto',
            name='numero',
            field=models.CharField(default='', max_length=10, verbose_name='Número da Nota Fiscal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nomeproduto',
            name='quantidade',
            field=models.CharField(default='', max_length=10, verbose_name='Quantidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicos',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor total do orçamento'),
        ),
        migrations.AlterField(
            model_name='gestao',
            name='politicas',
            field=models.TextField(max_length=300, verbose_name='Atualização'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valornota',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor total da nota'),
        ),
    ]
